# Permalinks
permalink:           pretty

# Setup
title:               Found Design
tagline:             A Traveling Design Mission 
url:                 http://found-design.co
paginate:            1
baseurl:             "http://found-design.co"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Nitzan Hermon
  url:               https://byed.it
  email:             x@byed.it

# Custom vars
version:             2.0.0
github:
  repo:              

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
